### ISSUE TITLE
Can we use delegate.cash to associate a multisig cold wallet to a hot wallet?

### ISSUE THREAD

**Issue by AppinventivSiyaKesarwani** [delegatecash/delegation-registry#32]
I wanted to know whether the functionality of claiming airdrops and free gifts can be achieved by multisig wallets or not? Can we call the delegate for NFT function ftom multisig wallet and then assign a hot wallet which will be able to accept the airdrops without disturbing the NFT stored in the wallet or not?

**Comment by 0xfoobar** [comment]
Yep! It's all onchain, so fully compatible with multisigs like Gnosis Safe. Just use WalletConnect!
